#-----------Table interactions-----------
#Drop functions for work purpouse.
DROP TABLE games;

#Creates a fresh table game_id as reference key, and auto generated game_id number.
CREATE TABLE games(
game_id INT NOT NULL AUTO_INCREMENT,
game_name VARCHAR(45),
PRIMARY KEY (game_id)
);

#-----------Scripts for functionality-----------
#Create a new Game with autogenerated positioning and unique game_id.
INSERT INTO tournament.games(game_name) VALUES(game_name);

#Delete a game from list, use game_id as reference to which game you want to remove.
DELETE FROM tournament.games WHERE game_id="";

#Make changes to the table.
UPDATE tournament.games
SET game_name="" #New name of Game
WHERE game_id=""; #What game_id you want to change for.


#-----------Visual scripts-----------
#Shows a image of Games table with all data inputs.
SELECT * FROM tournament.games;

#Shows a image of only Game
SELECT game_name FROM tournament.games;

#Shows a image of only game_id.
SELECT game_id FROM tournament.games;

DESCRIBE games;